# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailveryfyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('men', '\u7537'), ('man', '\u5973')], default='men', max_length=6),
        ),
    ]
