# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-05 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180811_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annalid', models.IntegerField(default=0, max_length=10, verbose_name='\u4e3b\u952e')),
                ('attrname', models.CharField(max_length=20, verbose_name='\u5c5e\u6027\u540d\u79f0')),
                ('features', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('progress', models.IntegerField(max_length=3, verbose_name='\u8bc4\u5206\u767e\u5206\u6bd4')),
                ('index', models.IntegerField(default=100, verbose_name='\u987a\u5e8f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('status', models.IntegerField(default=0, max_length=1, verbose_name='\u5408\u683c\u4e0e\u5426')),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u5c5e\u6027',
                'verbose_name_plural': '\u4e2a\u4eba\u5c5e\u6027',
            },
        ),
    ]
