# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-05 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='annalid',
            field=models.IntegerField(default=0, verbose_name='\u4e3b\u952e'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='\u8bc4\u5206\u767e\u5206\u6bd4'),
        ),
    ]
