# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-05 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181005_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u5408\u683c\u4e0e\u5426'),
        ),
    ]
