# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-05 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_attribute_annalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
            preserve_default=False,
        ),
    ]
