# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-05 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_attribute_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='UserAttr',
        ),
    ]
