# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181020_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ipaddr',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='\u767b\u5f55IP'),
        ),
    ]
